# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# cvs.yaml  (taints removed; everything else unchanged)

apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: $CLUSTER_NAME
  region: $AWS_REGION
  version: "1.31"

cloudWatch:
  clusterLogging:
    enableTypes: ["*"]

iam:
  withOIDC: true

managedNodeGroups:
  - name: cvs-gpu
    instanceType: g6.xlarge
    desiredCapacity: 2
    minSize: 2
    maxSize: 2
    labels:
      role: cvs-gpu

  - name: milvus-query
    instanceType: r7i.4xlarge  # 16 vCPU, 128 GB RAM
    desiredCapacity: 1
    minSize: 1
    maxSize: 1
    volumeSize: 120
    labels:
      nodegroup: milvus
      role: milvus-query
      memory-type: high
    taints:
      - key: dedicated
        value: querynode
        effect: NoExecute

  - name: general-compute
    instanceType: m6i.2xlarge
    desiredCapacity: 5
    minSize: 5
    maxSize: 5

  - name: optimized-compute
    instanceType: c6i.2xlarge
    desiredCapacity: 1
    minSize: 1
    maxSize: 1
